//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyappDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateList
    {
        public string SName { get; set; }
        public string StateCname { get; set; }
        public int SId { get; set; }
    }
}
